[tool.poetry]
name = "onepw-receiver"
version = "0.1.0"
description = ""
authors = ["fant5y <vroni@salala.de>"]
readme = "README.md"
packages = [
    { include = "onepw_receiver", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
onepasswordconnectsdk = "^1"
rich = "^13"
python-dotenv = "^1.0.1"
tomlkit = "^0.12.4"

[tool.poetry.group.dev.dependencies]
black = { extras = ["d"], version = "^24" }
isort = "^5"
mypy = "^1.9"
pipreqs = "^0.5"
pylint = "^3.1.0"


[tool.black]
line-length = 99
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 99
extra_standard_library = ["pytest"]

[mypy]
warn_return_any = false
warn_unused_configs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
